import os
import time
from typing import Optional
from datetime import date
import numpy as np
import requests
import pymysql


def read_f2b_output() -> np.ndarray[str, np.dtype[str]]:
    """
    reads the output generated by the f2b shell script.

    Returns:
        np.ndarray[str, np.dtype[str]]: _description_
    """
    ips = []
    with open("./f2b.txt", "r", encoding="utf-8") as file:
        for ip in file:
            ip = ip.replace("\n", "")
            ips.append(ip)
    return np.array(ips)


def get_ip_metadata(
    ip: str,
) -> Optional[tuple[str, str, int, str, float, str]]:
    """
    Extracts more data from the given ip using an external service.

    Args:
        ip (str): ip to be data mined

    Returns:
        Optional[tuple[str, str, int, float, float, float]]: country, city, cp, lat, lon, isp
    """
    request = None
    try:
        url2 = """https://ipinfo.io/""" + ip + """?token="""
        request = requests.get(url2)

    except Exception as e:
        print(e)
    if request is None:
        return
    data = request.json()
    country: str = data["country"]
    city: str = data["city"]
    cp: int = data["postal"]
    lat: str = data["loc"]
    isp: str = data["org"]
    return country, city, cp, lat, isp


def insert_data_in_db(ips: np.ndarray[str, np.dtype[str]]):
    """Inserts the data in the database.
    nnection = pymysql.connect(host='localhost', user='root', password='', database='db_emp', charset='utf8mb4', cursorclass=pymysql.cursors.DictCursor)
    Args:
        ips (np.ndarray[str, np.dtype[str]]): ips to insert
    """
    db = pymysql.connect(
        host="",
        user="Fail2Ban",
        password="",
        database="Fail2Ban",
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor,
    )
    cursor = db.cursor()
    today = date.today()
    d1 = today.strftime("%Y-%m-%d")
    for ip in ips:
        try:
            country, city, cp, lat, isp = get_ip_metadata(ip)
            cord = lat.split(',')
            if country is not None:
                sql = (
                    "INSERT INTO `grafana`(`ip`, `country`, `city`, `zip`, `lat`, `isp`, `datum`, `lon`) VALUES ('"
                    + ip
                    + "','"
                    + country
                    + "','"
                    + city
                    + "','"
                    + cp
                    + "','"
                    + cord[0]
                    + "','"
                    + isp
                    + "','"
                    + d1
                    + "','"
                    + cord[1]
                    + "')"
                )
                cursor.execute(sql)
                db.commit()
                time.sleep(1.5)
        except Exception as e:
            print(e)
            time.sleep(1.5)


if __name__ == "__main__":
    ips = read_f2b_output()
    insert_data_in_db(ips)
